---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/infrastructure/controllers
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-config
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 10s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/infrastructure/config
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-rbac
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 10s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/infrastructure/rbac
  prune: true
  wait: true
